modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved unless stated otherwise. Distribution permission is given to FeedTheBeast and CurseForge for use in modpacks"
[[mods]]
modId="javd"
version = "${mod_version}"
displayName="Just Another Void Dimension"
logoFile="assets/javd/logo.png"
credits=""
authors="UnRealDinnerbone"
description="Adds a void dimension to the game."
[[dependencies.javd]]
modId = "neoforge"
required = true
versionRange = "[1.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.javd]]
modId = "minecraft"
required = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
[[dependencies.javd]]
modId = "trenzalore"
required = true
versionRange = "[${trenzalore_version},)"
ordering = "NONE"
side = "BOTH"